server:
  port: 8081

spring:
  application:
    name: busbooking
  datasource:
    url: jdbc:mysql://localhost:3306/busbooking
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update




