spring:
  datasource:
    url: jdbc:mysql://busbooking.cidw668kk5wh.us-east-1.rds.amazonaws.com:3306/busbooking
    username: admin
    password: Booking123
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    user:
      name: admin
      password: admin123

jwt:
  secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
  expiration: 86400000

